version: '2.1'
executors:
    golang:
        docker:
            - image: golang:1.13.3-alpine

jobs:
    lint:
        executor: golang
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client
            - checkout
            - run:
                name: Lint
                command: bin/lint

    test:
        executor: golang
        working_directory: ~/repo
        steps:
            - run:
                name: Install requirements
                command: apk add git openssh-client gcc musl-dev
            - checkout
            - run:
                name: Download modules
                command: go mod download
            - run:
                name: Test
                command: bin/test
            - run:
                name: push code coverage report to codecov
                command: |
                    apk add bash curl
                    curl -s https://codecov.io/bash | bash

    dockerhub:
        docker:
            - image: docker:18.09.7-git
        working_directory: ~/repo
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Authenticate to dockerhub
                command: echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_LOGIN} --password-stdin
            - run:
                name: Build and push docker image
                command: |
                    version=latest
                    if [[ ! -z ${CIRCLE_TAG} ]]; then \
                        version=${CIRCLE_TAG}; \
                    fi

                    docker_tag=${DOCKERHUB_ORGANIZATION}/${CIRCLE_PROJECT_REPONAME}:${version}

                    docker build . -t ${docker_tag}
                    docker push ${docker_tag}

workflows:
    version: '2.1'
    tests:
        jobs:
            - lint
            - test

    dockerhub:
        jobs:
            - dockerhub:
                context: global
                filters:
                    tags:
                        only: /^[0-9]+.[0-9]+.[0-9]+$/
                    branches:
                        only: master
